### ISSUE TITLE
Issues deploying to Heroku

### ISSUE THREAD

**Issue by brandonparsons** [davidcelis/recommendable#101]
Hi there,

I'm having some problems trying to use the recommendable gem on Heroku.

```
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
remote:        and using the production group of your Gemfile.
remote:        This may be intentional, if you expected rake tasks to be run
remote:        cancel the build (CTRL+C) and fix the error then commit the fix:
remote:        rake aborted!
remote:        ArgumentError: invalid uri scheme ''
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:390:in `_parse_options'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:73:in `initialize'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/redis-3.2.0/lib/redis.rb:31:in `new'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/redis-3.2.0/lib/redis.rb:31:in `initialize'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/recommendable-2.2.0/lib/recommendable/configuration.rb:51:in `new'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/recommendable-2.2.0/lib/recommendable/configuration.rb:51:in `initialize'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/recommendable-2.2.0/lib/recommendable/configuration.rb:71:in `new'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/recommendable-2.2.0/lib/recommendable/configuration.rb:71:in `configure'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/recommendable-2.2.0/lib/recommendable/orm/active_record.rb:6:in `<top (required)>'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/recommendable-2.2.0/lib/recommendable.rb:47:in `<top (required)>'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/config/application.rb:15:in `<top (required)>'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/Rakefile:4:in `require'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/Rakefile:4:in `<top (required)>'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
remote:        /tmp/build_e27b023cfbd1ef86edd872971fd846dd/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
remote:        vendor/bundle/bin/rake:16:in `load'
remote:        vendor/bundle/bin/rake:16:in `<main>'
```

I've tried only initializing recommendable if there is an environment variable present for Redis, but it doesn't seem to help.

Have you seen anything like this before?

**Comment by danielricecodes** [comment]
I arrived here because of the exact same issue.  I use Heroku and have RedisCloud as my redis provider on my production and staging databases, but use Heroku Redis on Review apps. 

I configured my `cable.yml` file like this and it works perfectly across all my Heroku environments.

```yml
production:
  adapter: redis
  url: "<%= ENV.fetch('REDISCLOUD_URL') { ENV['REDIS_URL'] } %>"
```
